### ISSUE TITLE
Requirements and Specifications 초안

### ISSUE THREAD

**Issue by DoohyunHwang97** [swsnu/swppfall2022-team20#1]
오타나 내용적인 부분에서 수정, 보완하면 좋을 것들 얘기해시면 될듯합니다!
[requirementsAndSpecifications.md](https://github.com/swsnu/swppfall2022-team20/files/9791341/requirementsAndSpecifications.md)

**Comment by Quantee-OH** [comment]
저는 이 정도면 충분하다고 생각하고, interface만 문서에 같이 붙히면 될거 같습니다!

**Comment by DoohyunHwang97** [comment]
[requirementsAndSpecifications.md](https://github.com/swsnu/swppfall2022-team20/files/9791485/requirementsAndSpecifications.md)
interface 추가했습니다
wiki에 추가하는 것이 pdf였나요?

**Comment by Quantee-OH** [comment]
wiki가 md파일이고 조교님께 메일보내는 것이 pdf인걸로 알고있습니다!

**Comment by DoohyunHwang97** [comment]
네 위키에 추가했는데 확인해보시고 수정할 것 있으면 수정하고 pdf로 보내면 될듯합니다!

**Comment by Quantee-OH** [comment]
interface도 충분한거 같습니다.

**Comment by DoohyunHwang97** [comment]
[requirementsAndSpecifications.pdf](https://github.com/swsnu/swppfall2022-team20/files/9791544/requirementsAndSpecifications.pdf)
넵 그럼 이 파일로 최종제출하겠습니다.
