### ISSUE TITLE
[Testing Session] Feedback

### ISSUE THREAD

**Issue by Quantee-OH** [swsnu/swppfall2022-team20#70]
SWPPfall2022-Team20
Service name: Stylestargram (Recommend pants by your size)

Feedback

**Comment by lukaspark16** [comment]
회원가입 페이지에 들어가면 id랑 pw값이 '테스트'로 남아있어요! 고생하셨습니다 🥇

**Comment by gkgkgkgkgk73** [comment]
회원가입 창에서 이메일 형식이 아니어도 입력이 됩니다!!

**Comment by engineerA314** [comment]
user profile 페이지의 input 창이 정렬되어 있지 않습니다. 이 부분이 정렬되고, 좀 더 설명이 추가되었으면 좋겠습니다.
전반적으로 css 디자인 구현이 부족한 것 같습니다. 수고하셨습니다.

**Comment by Whiteppanda** [comment]
회원가입 페이지와 로그인 페이지의 input창이 정렬되면 좋겠어요. 
홈페이지에서 추천 옷이 뜰때 맨 에 home이 살짝 보이는데 없애면 좋겠어요 화이팅!

**Comment by hanaisreal** [comment]
아이템 클릭하면 바로 무신사로 넘어가서 좋았어요! 회원가입시에 맞는 사이즈를 작성하지 않으면 회원가입이 안된다는 점이 아쉬웠습니다!

**Comment by GAON25** [comment]
회원가입 시 물음표를 누르지 않더라도 사이즈 범위를 확인할 수 있게 하면 좋을 거 같습니다! 아니라면 범위를 초과한 숫자를 입력한 경우 경고창이 되면 더 좋을 거 같습니다! 유용한 기능이라 기대가 많이 됩니다

**Comment by yunwkgus** [comment]
정말 예쁜 것 같아요! 지금 준비하신 기능이 다 구현된다면 잘 써볼 것 같습니다!

**Comment by SungwonShim** [comment]
아직 완성도가 떨어지는 점이 아쉬운 것 같습니다! 지금 구현해 둔 버튼이라도 돌아간다면 보기 예쁠 것 같습니다.

**Comment by askrid** [comment]
옷을 클릭하고 바깥을 누르면 'back'을 누른 것처럼 뒤로 갔으면 좋겠습니다.

**Comment by ozeeeno** [comment]
어떻게 사이즈를 재는지에 대한 기능이 추가된다고 말씀하셨는데 해당 기능이 추가되면 유용할 것 같습니다.

**Comment by jhm1313** [comment]
아직 구현이 안 된 부분이 많은 것 같아 아쉽지만, 구현이 끝나면 좋은 서비스일 것 같습니다.
회원가입 시 도움말에 대한 기능이 인상적이었습니다.

**Comment by nyminna** [comment]
회원가입시 도움말이 좋았습니다. 바로 옆에 inch인지 cm인지 적어주면 더 좋을 것 같습니다.
사이즈 선택 후 바로 그 사이즈가 선택된 상태의 사이트가 열릴 계획이라고 하셨는데 기대됩니다!

**Comment by taeminers** [comment]
두 분 정말 고생하셨습니다. bug 만 고치시고 기능들만 잘 추가하시면 완성도 있는 서비스가 될 것 같습니다.

**Comment by Young-in** [comment]
로그인이 된 상태에서 url에 직접 접근했을때 로그아웃 된것 같이 로그인 페이지로 넘어갔습니다.

리뷰를 적는 버튼이 따로 나와있으면 좋을 것 같아요.

**Comment by vietman2** [comment]
로그인 후 첫 화면에서 탑바 아래에 메인 화면이 가리는 버그가 있습니다

**Comment by insung151** [comment]
고생하셨습니다.
데이터가 더 추가되면 좋을거 같습니다.

**Comment by keetae423** [comment]
- 현재 전반적인 기능 구현이 약간 부족해 보입니다. scrap 기능이나 user profile에서 확인할 수 있는 주요 화면부터 구현해주시면 좋을 것 같아요.
